<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrestadorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $prestadores = [
            [
                'nome' => 'Ana Souza',
                'logradouro' => 'Av. Paulista',
                'bairro' => 'Bela Vista',
                'numero' => '1000',
                'latitude' => -23.561684,
                'longitude' => -46.656139,
                'cidade' => 'São Paulo',
                'UF' => 'SP',
                'situacao' => true,
            ],
            [
                'nome' => 'Carlos Oliveira',
                'logradouro' => 'Rua XV de Novembro',
                'bairro' => 'Centro',
                'numero' => '210',
                'latitude' => -25.429596,
                'longitude' => -49.271272,
                'cidade' => 'Curitiba',
                'UF' => 'PR',
                'situacao' => true,
            ],
            [
                'nome' => 'Fernanda Lima',
                'logradouro' => 'Rua das Laranjeiras',
                'bairro' => 'Laranjeiras',
                'numero' => '50',
                'latitude' => -22.932728,
                'longitude' => -43.180574,
                'cidade' => 'Rio de Janeiro',
                'UF' => 'RJ',
                'situacao' => false,
            ],
            [
                'nome' => 'João Pereira',
                'logradouro' => 'Av. Sete de Setembro',
                'bairro' => 'Centro',
                'numero' => '1750',
                'latitude' => -12.973039,
                'longitude' => -38.508489,
                'cidade' => 'Salvador',
                'UF' => 'BA',
                'situacao' => true,
            ],
            [
                'nome' => 'Marina Silva',
                'logradouro' => 'Av. Getúlio Vargas',
                'bairro' => 'Funcionários',
                'numero' => '340',
                'latitude' => -19.932014,
                'longitude' => -43.922356,
                'cidade' => 'Belo Horizonte',
                'UF' => 'MG',
                'situacao' => true,
            ],
            [
                'nome' => 'Lucas Santos',
                'logradouro' => 'Rua dos Andradas',
                'bairro' => 'Centro Histórico',
                'numero' => '700',
                'latitude' => -30.027704,
                'longitude' => -51.228735,
                'cidade' => 'Porto Alegre',
                'UF' => 'RS',
                'situacao' => false,
            ],
            [
                'nome' => 'Beatriz Ramos',
                'logradouro' => 'Rua Augusta',
                'bairro' => 'Consolação',
                'numero' => '1350',
                'latitude' => -23.553501,
                'longitude' => -46.658748,
                'cidade' => 'São Paulo',
                'UF' => 'SP',
                'situacao' => true,
            ],
            [
                'nome' => 'Gabriel Costa',
                'logradouro' => 'Av. Boa Viagem',
                'bairro' => 'Boa Viagem',
                'numero' => '220',
                'latitude' => -8.117445,
                'longitude' => -34.894278,
                'cidade' => 'Recife',
                'UF' => 'PE',
                'situacao' => false,
            ],
            [
                'nome' => 'Patrícia Fernandes',
                'logradouro' => 'Av. das Nações Unidas',
                'bairro' => 'Brooklin',
                'numero' => '18000',
                'latitude' => -23.626836,
                'longitude' => -46.700532,
                'cidade' => 'São Paulo',
                'UF' => 'SP',
                'situacao' => true,
            ],
            [
                'nome' => 'Rafael Lopes',
                'logradouro' => 'Av. Aguanambi',
                'bairro' => 'Benfica',
                'numero' => '1200',
                'latitude' => -3.748148,
                'longitude' => -38.536358,
                'cidade' => 'Fortaleza',
                'UF' => 'CE',
                'situacao' => false,
            ],
            [
                'nome' => 'Juliana Mendes',
                'logradouro' => 'Rua João Alfredo',
                'bairro' => 'Cidade Baixa',
                'numero' => '456',
                'latitude' => -30.041707,
                'longitude' => -51.220826,
                'cidade' => 'Porto Alegre',
                'UF' => 'RS',
                'situacao' => true,
            ],
            [
                'nome' => 'Tiago Neves',
                'logradouro' => 'Av. Santos Dumont',
                'bairro' => 'Aldeota',
                'numero' => '800',
                'latitude' => -3.730962,
                'longitude' => -38.515382,
                'cidade' => 'Fortaleza',
                'UF' => 'CE',
                'situacao' => true,
            ],
            [
                'nome' => 'Larissa Rocha',
                'logradouro' => 'Av. Brasil',
                'bairro' => 'Centro',
                'numero' => '980',
                'latitude' => -22.904927,
                'longitude' => -43.189017,
                'cidade' => 'Rio de Janeiro',
                'UF' => 'RJ',
                'situacao' => false,
            ],
            [
                'nome' => 'Vinícius Almeida',
                'logradouro' => 'Rua Aracaju',
                'bairro' => 'Praia Grande',
                'numero' => '128',
                'latitude' => -24.007329,
                'longitude' => -46.412232,
                'cidade' => 'Praia Grande',
                'UF' => 'SP',
                'situacao' => true,
            ],
            [
                'nome' => 'Camila Teixeira',
                'logradouro' => 'Av. João Pessoa',
                'bairro' => 'Centro',
                'numero' => '545',
                'latitude' => -30.039989,
                'longitude' => -51.217718,
                'cidade' => 'Porto Alegre',
                'UF' => 'RS',
                'situacao' => true,
            ],
            [
                'nome' => 'Daniel Moraes',
                'logradouro' => 'Av. Rio Branco',
                'bairro' => 'Centro',
                'numero' => '222',
                'latitude' => -22.908333,
                'longitude' => -43.197823,
                'cidade' => 'Rio de Janeiro',
                'UF' => 'RJ',
                'situacao' => false,
            ],
            [
                'nome' => 'Amanda Ribeiro',
                'logradouro' => 'Av. Presidente Vargas',
                'bairro' => 'Centro',
                'numero' => '1001',
                'latitude' => -22.903539,
                'longitude' => -43.209587,
                'cidade' => 'Rio de Janeiro',
                'UF' => 'RJ',
                'situacao' => true,
            ],
            [
                'nome' => 'Felipe Martins',
                'logradouro' => 'Av. das Américas',
                'bairro' => 'Barra da Tijuca',
                'numero' => '7777',
                'latitude' => -23.003659,
                'longitude' => -43.365669,
                'cidade' => 'Rio de Janeiro',
                'UF' => 'RJ',
                'situacao' => false,
            ],
            [
                'nome' => 'Isabela Castro',
                'logradouro' => 'Rua Padre Chagas',
                'bairro' => 'Moinhos de Vento',
                'numero' => '999',
                'latitude' => -30.027704,
                'longitude' => -51.214873,
                'cidade' => 'Porto Alegre',
                'UF' => 'RS',
                'situacao' => true,
            ],
            [
                'nome' => 'Matheus Farias',
                'logradouro' => 'Av. Eng. Roberto Freire',
                'bairro' => 'Ponta Negra',
                'numero' => '1234',
                'latitude' => -5.872789,
                'longitude' => -35.179109,
                'cidade' => 'Natal',
                'UF' => 'RN',
                'situacao' => false,
            ],
            [
                'nome' => 'Sabrina Nogueira',
                'logradouro' => 'Rua 24 de Maio',
                'bairro' => 'Centro',
                'numero' => '150',
                'latitude' => -3.746802,
                'longitude' => -38.526161,
                'cidade' => 'Fortaleza',
                'UF' => 'CE',
                'situacao' => true,
            ],
            [
                'nome' => 'Hugo Leal',
                'logradouro' => 'Rua das Acácias',
                'bairro' => 'Jardim Botânico',
                'numero' => '401',
                'latitude' => -22.964557,
                'longitude' => -43.223087,
                'cidade' => 'Rio de Janeiro',
                'UF' => 'RJ',
                'situacao' => true,
            ],
            [
                'nome' => 'Débora Silva',
                'logradouro' => 'Av. Dom Luís',
                'bairro' => 'Meireles',
                'numero' => '950',
                'latitude' => -3.722522,
                'longitude' => -38.499325,
                'cidade' => 'Fortaleza',
                'UF' => 'CE',
                'situacao' => false,
            ],
            [
                'nome' => 'Rodrigo Batista',
                'logradouro' => 'Rua do Sol',
                'bairro' => 'Boa Vista',
                'numero' => '84',
                'latitude' => -8.063149,
                'longitude' => -34.871139,
                'cidade' => 'Recife',
                'UF' => 'PE',
                'situacao' => True,
            ],
            [
                'nome' => 'Letícia Gomes',
                'logradouro' => 'Av. Atlântica',
                'bairro' => 'Copacabana',
                'numero' => '3806',
                'latitude' => -22.971177,
                'longitude' => -43.182543,
                'cidade' => 'Rio de Janeiro',
                'UF' => 'RJ',
                'situacao' => true,
            ],
        ];

        foreach ($prestadores as $prestador) {
            DB::table('prestador')->insert([
                'nome' => $prestador['nome'],
                'logradouro' => $prestador['logradouro'],
                'bairro' => $prestador['bairro'],
                'numero' => $prestador['numero'],
                'latitude' => $prestador['latitude'],
                'longitude' => $prestador['longitude'],
                'cidade' => $prestador['cidade'],
                'UF' => $prestador['UF'],
                'situacao' => $prestador['situacao'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
